### PR TITLE
Feature Strict Mode

### PR DESCRIPTION
**Pull request by SuperNova74-K**
Added Strict Mode Feature

### CODE REVIEW

**Review by OmarElgammal1 — APPROVED** [review]
Looks good

**Comment by Black-Hack** [comment]
Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?

**Comment by Black-Hack** [comment]
Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.

**Comment by OmarElgammal1** [comment]
> Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?

nope because they will be able to trigger it whenever they want to, and they might abuse this feature.

**Comment by Black-Hack** [comment]
> > Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?
> 
> nope because they will be able to trigger it whenever they want to, and they might abuse this feature.

How can someone abuse it if they can only toggle it for themselves? They could just as easily not turn it on from the beginning.

**Comment by OmarElgammal1** [comment]
> Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.

Well it was suggested by multiple users as they felt the bot was too strict.
So this feature will make it a bit easier and it won't kick the ones who has strict mode off.

**Comment by OmarElgammal1** [comment]
> > > Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?
> > 
> > 
> > nope because they will be able to trigger it whenever they want to, and they might abuse this feature.
> 
> How can someone abuse it if they can only toggle it for themselves? They could just as easily not turn it on from the beginning.

yes but they might  turn it on right before getting a red card, then turning it on again. I think it's better to require the admin to know beforehand if someone needs strict mode

**Comment by Black-Hack** [comment]
> > Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.
> 
> Well it was suggested by multiple users as they felt the bot was too strict. So this feature will make it a bit easier and it won't kick the ones who has strict mode off.

Yes, I agree, but don't make it turned on by default.

**Comment by Black-Hack** [comment]
> > > > Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?
> > > 
> > > 
> > > nope because they will be able to trigger it whenever they want to, and they might abuse this feature.
> > 
> > 
> > How can someone abuse it if they can only toggle it for themselves? They could just as easily not turn it on from the beginning.
> 
> yes but they might turn it on right before getting a red card, then turning it on again. I think it's better to require the admin to know beforehand if someone needs strict mode

Sounds good! Thanks for your time.

**Comment by OmarElgammal1** [comment]
> > > Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.
> > 
> > 
> > Well it was suggested by multiple users as they felt the bot was too strict. So this feature will make it a bit easier and it won't kick the ones who has strict mode off.
> 
> Yes, I agree, but don't make it turned on by default.

The normal bot functionalities = strict mode on
the new feature is to allow someone to turn it off so they can stay in server when they get a red card.

**Comment by OmarElgammal1** [comment]
> > > Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.
> > 
> > 
> > Well it was suggested by multiple users as they felt the bot was too strict. So this feature will make it a bit easier and it won't kick the ones who has strict mode off.
> 
> Yes, I agree, but don't make it turned on by default.

The normal bot functionallities = strict mode on

**Comment by OmarElgammal1** [comment]
> > > > > Are you sure it's a good idea to allow admins to toggle strict mode for users? Wouldn't it be better idea to only allow users to toggle strict mode for themselves?
> > > > 
> > > > 
> > > > nope because they will be able to trigger it whenever they want to, and they might abuse this feature.
> > > 
> > > 
> > > How can someone abuse it if they can only toggle it for themselves? They could just as easily not turn it on from the beginning.
> > 
> > 
> > yes but they might turn it on right before getting a red card, then turning it on again. I think it's better to require the admin to know beforehand if someone needs strict mode
> 
> Sounds good! Thanks for your time.

Happy to help

**Comment by Black-Hack** [comment]
> > > > Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.
> > > 
> > > 
> > > Well it was suggested by multiple users as they felt the bot was too strict. So this feature will make it a bit easier and it won't kick the ones who has strict mode off.
> > 
> > 
> > Yes, I agree, but don't make it turned on by default.
> 
> The normal bot functionalities = strict mode on the new feature is to allow someone to turn it off so they can stay in server when they get a red card.

Sounds good too! Thanks again for your time!

**Comment by OmarElgammal1** [comment]
> > > > > Also, I think that such a drastic change in behavior should be opt-in rather than opt-out.
> > > > 
> > > > 
> > > > Well it was suggested by multiple users as they felt the bot was too strict. So this feature will make it a bit easier and it won't kick the ones who has strict mode off.
> > > 
> > > 
> > > Yes, I agree, but don't make it turned on by default.
> > 
> > 
> > The normal bot functionalities = strict mode on the new feature is to allow someone to turn it off so they can stay in server when they get a red card.
> 
> Sounds good too! Thanks again for your time!

No problem

**Comment by OmarElgammal1** [comment]
However there are multiple conflicts due to this branch being behind with commits, especially with client.py and penalty_scheduler.py.
@SuperNova74-K

**Pull request closed without merging**
